name: build unity IOS plugins by tangy

on: 
  workflow_dispatch:
  push:
    paths: 
      - unity/native_src/**
      - unity/native_src_ourv8/**
      - unreal/Puerts/Source/JsEnv/Private/V8InspectorImpl.cpp
      - unreal/Puerts/Source/JsEnv/Private/V8InspectorImpl.h
      - unreal/Puerts/Source/JsEnv/Private/PromiseRejectCallback.hpp
      - .github/workflows/build_unity_plugins.yml

env:
  RUNID: 613573412

jobs:
  ios:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Use Xcode 12.0 for x86
        run: sudo xcode-select -switch "/Applications/Xcode_12.app"
      - name: Build
        run: |
          cd unity/native_src
          sh ./make_ios.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_V8
